---
features:
  - |
    Jiralert is a service which runs alongside Prometheus Alertmanager to
    generate Jira tickets from alerts. It provides the glue between the
    Prometheus Alertmanager webhook notification service and Jira. See
    https://github.com/prometheus-community/jiralert for more details.
