---
- import_tasks: config.yml

- import_tasks: bootstrap_service.yml

# NOTE(kiennt): vitrage-collector are removed in Stein cycle.
#               Upgrade to Stein should remove vitrage-collector
#               container. This task should be removed in
#               T cycle.
- name: Remove vitrage-collector container
  become: true
  kolla_docker:
    name: vitrage_collector
    action: remove_container

- name: Flush handlers
  meta: flush_handlers
