---
- import_tasks: config-host.yml

- import_tasks: config.yml

- set_fact: secondary_addresses={{ hostvars[inventory_hostname]['ansible_' + api_interface].get('ipv4_secondaries', []) | map(attribute='address') | list }}

- name: Stopping all slave keepalived containers
  become: true
  kolla_docker:
    action: "stop_container"
    common_options: "{{ docker_common_options }}"
    name: "keepalived"
  when: kolla_internal_vip_address not in secondary_addresses
  notify:
    - Restart keepalived container

# NOTE(yoctozepto): haproxy role handlers should not be flushed early.
# site.yml handles all haproxy things in a dedicated play.
# This is to avoid extra haproxy service restart.
# See: https://bugs.launchpad.net/kolla-ansible/+bug/1875228
