---
- name: Setting sysctl values
  become: true
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes
  with_items:
    - { name: "vm.max_map_count", value: 262144}
  when:
    - set_sysctl | bool
    - inventory_hostname in groups['elasticsearch']

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ elasticsearch_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: elasticsearch_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ elasticsearch_services }}"
  notify:
    - Restart elasticsearch container

- name: Copying over elasticsearch service config files
  merge_yaml:
    sources:
      - "{{ role_path }}/templates/{{ item.key }}.yml.j2"
      - "{{ node_custom_config }}/elasticsearch.yml"
      - "{{ node_custom_config }}/elasticsearch/{{ item.key }}.yml"
      - "{{ node_custom_config }}/elasticsearch/{{ inventory_hostname }}/{{ item.key }}.yml"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ item.key }}.yml"
    mode: "0660"
  become: true
  register: elasticsearch_confs
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ elasticsearch_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over elasticsearch curator actions
  vars:
    service: "{{ elasticsearch_services['elasticsearch-curator'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/elasticsearch-curator/elasticsearch-curator-actions.yml"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/elasticsearch/elasticsearch-curator-actions.yml"
    - "{{ role_path }}/templates/elasticsearch-curator-actions.yml.j2"
  notify:
    - Restart elasticsearch-curator container

- name: Copying over elasticsearch curator crontab
  vars:
    service: "{{ elasticsearch_services['elasticsearch-curator'] }}"
  template:
    src: "{{ role_path }}/templates/elasticsearch-curator.crontab.j2"
    dest: "{{ node_config_directory }}/elasticsearch-curator/elasticsearch-curator.crontab"
    mode: "0660"
  become: true
  register: elasticsearch_curator_crontab
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool
  notify:
    - Restart elasticsearch-curator container

- name: Check elasticsearch containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    dimensions: "{{ item.value.dimensions }}"
    environment: "{{ item.value.environment|default(omit) }}"
  register: check_elasticsearch_containers
  when:
    - kolla_action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ elasticsearch_services }}"
  notify:
    - "Restart {{ item.key }} container"
