---
- name: Restart horizon container
  vars:
    service_name: "horizon"
    service: "{{ horizon_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    environment: "{{ service.environment }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - horizon_config_json is changed
      or horizon_conf is changed
      or horizon_local_settings is changed
      or horizon_custom_local_settings is changed
      or policy_jsons is changed
      or check_horizon_container is changed
