---
- name: Restart opendaylight container
  vars:
    service_name: "opendaylight"
    service: "{{ opendaylight_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    privileged: "{{ service.privileged | default(False) }}"
    dimensions: "{{ service.dimensions }}"
    tty: "{{ service.tty }}"
  when:
    - kolla_action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opendaylight_config_json is changed
      or opendaylight_config_start_odl is changed
      or opendaylight_config_custom_props is changed
      or opendaylight_config_jetty is changed
      or opendaylight_config_features is changed
      or opendaylight_config_ovsdb is changed
      or opendaylight_config_tomcat is changed
      or opendaylight_config_logging is changed
      or opendaylight_config_netvirt is changed
      or opendaylight_config_netvirt_acl is changed
      or opendaylight_config_env is changed
      or opendaylight_config_akka is changed
      or opendaylight_config_modules is changed
      or opendaylight_config_module_shards is changed
      or opendaylight_config_10_rest_connector is changed
      or check_opendaylight_containers is changed
