---
- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - deploy-guide-jobs
    check:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-oraclelinux-source
        - kolla-ansible-ubuntu-source-ceph
        - kolla-ansible-centos-source-ceph
        - kolla-ansible-oraclelinux-source-ceph
        - kolla-ansible-bifrost-centos-source:
            files: ^ansible\/roles\/bifrost\/.*
        - kolla-ansible-ubuntu-source-zun:
            files: ^ansible\/roles\/zun\/.*
        - openstack-tox-lower-constraints
    gate:
      queue: kolla
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - openstack-tox-lower-constraints
